const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const sampleEntries = [
  {
    title: "Severance",
    type: "Series",
    genres: ["Sci-Fi", "Mystery", "Drama"],
    status: "WATCHING",
    rating: 9.5,
    notes: "Peak television. The tension in Lumon Industries is unmatched.",
    synopsis: "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives.",
    posterUrl: "https://image.tmdb.org/t/p/w500/hGOCi11dJ5nE8M2f03yY0z0eGqj.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/9faGSFi5jam6pDWGNd0p8JcJgXQ.jpg",
    releaseYear: 2022,
    runtimeMin: 55,
    progressText: "S2 • E7",
    isTop10: false,
    isTop5Rec: true,
    top5Rank: 1,
    dateStarted: new Date("2024-08-10"),
  },
  {
    title: "Arcane",
    type: "Series",
    genres: ["Animation", "Action", "Sci-Fi"],
    status: "WATCHING",
    rating: 9.8,
    notes: "Visually breathtaking, heartbreaking story of Vi and Jinx.",
    synopsis: "Amid the conflict between twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and convictions.",
    posterUrl: "https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn397Fvd247pH.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/fqv8v6AycXKsivp1TddutaLIx0J.jpg",
    releaseYear: 2021,
    runtimeMin: 42,
    progressText: "S2 • E6",
    isTop10: false,
    isTop5Rec: true,
    top5Rank: 2,
    dateStarted: new Date("2024-08-15"),
  },
  {
    title: "Dune: Part Two",
    type: "Movie",
    genres: ["Sci-Fi", "Adventure", "Action"],
    status: "WATCHED",
    rating: 9.6,
    notes: "A cinematic triumph. The sound design alone deserves every accolade.",
    synopsis: "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    posterUrl: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5207bA.jpg",
    releaseYear: 2024,
    runtimeMin: 166,
    isTop10: true,
    top10Rank: 1,
    isTop5Rec: true,
    top5Rank: 3,
    dateWatched: new Date("2024-03-12"),
  },
  {
    title: "Spider-Man: Across the Spider-Verse",
    type: "Movie",
    genres: ["Animation", "Action", "Sci-Fi"],
    status: "WATCHED",
    rating: 9.7,
    notes: "Revolutionary animation style and an emotional father-daughter/son core.",
    synopsis: "After reuniting with Gwen Stacy, Brooklyn's full-time friendly neighborhood Spider-Man is catapulted across the Multiverse.",
    posterUrl: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    releaseYear: 2023,
    runtimeMin: 140,
    isTop10: true,
    top10Rank: 2,
    isTop5Rec: true,
    top5Rank: 4,
    dateWatched: new Date("2023-06-15"),
  },
  {
    title: "Succession",
    type: "Series",
    genres: ["Drama"],
    status: "WATCHED",
    rating: 9.5,
    notes: "The sharpest writing in the history of prestige TV drama.",
    synopsis: "The Roy family is known for controlling the biggest media and entertainment company in the world. However, their world changes when their aging father steps down from the company.",
    posterUrl: "https://image.tmdb.org/t/p/w500/7udW4b4hL0472eL4p1a7o55vC4M.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/zZqpaxMBdtkLVGkWvzrB47a74kG.jpg",
    releaseYear: 2018,
    runtimeMin: 60,
    isTop10: true,
    top10Rank: 3,
    isTop5Rec: true,
    top5Rank: 5,
    dateWatched: new Date("2023-06-01"),
  },
  {
    title: "Oppenheimer",
    type: "Movie",
    genres: ["Drama", "History"],
    status: "WATCHED",
    rating: 9.3,
    notes: "Nolan at his most restrained yet devastatingly impactful.",
    synopsis: "The story of J. Robert Oppenheimer’s role in the development of the atomic bomb during World War II.",
    posterUrl: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    releaseYear: 2023,
    runtimeMin: 180,
    isTop10: true,
    top10Rank: 4,
    dateWatched: new Date("2023-07-28"),
  },
  {
    title: "Spirited Away",
    type: "Movie",
    genres: ["Animation", "Fantasy", "Adventure"],
    status: "WATCHED",
    rating: 9.6,
    notes: "Miyazaki's magnum opus. Eternal magic and nostalgia.",
    synopsis: "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    posterUrl: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/bXNvzjYEyO84xVzT489jL336Yg4.jpg",
    releaseYear: 2001,
    runtimeMin: 125,
    isTop10: true,
    top10Rank: 5,
    dateWatched: new Date("2022-04-10"),
  },
  {
    title: "Interstellar",
    type: "Movie",
    genres: ["Sci-Fi", "Drama", "Adventure"],
    status: "WATCHED",
    rating: 9.8,
    notes: "Love transcends time and space. Zimmer's score gives goosebumps every time.",
    synopsis: "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
    posterUrl: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    releaseYear: 2014,
    runtimeMin: 169,
    isTop10: true,
    top10Rank: 6,
    dateWatched: new Date("2022-11-20"),
  },
  {
    title: "Breaking Bad",
    type: "Series",
    genres: ["Drama", "Crime", "Thriller"],
    status: "WATCHED",
    rating: 9.9,
    notes: "Flawless character arc. Walter White's descent is television perfection.",
    synopsis: "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family's financial future.",
    posterUrl: "https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
    releaseYear: 2008,
    runtimeMin: 47,
    isTop10: true,
    top10Rank: 7,
    dateWatched: new Date("2021-08-14"),
  },
  {
    title: "The Dark Knight",
    type: "Movie",
    genres: ["Action", "Crime", "Drama"],
    status: "WATCHED",
    rating: 9.7,
    notes: "Heath Ledger's Joker defined modern cinema villains.",
    synopsis: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.",
    posterUrl: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
    releaseYear: 2008,
    runtimeMin: 152,
    isTop10: true,
    top10Rank: 8,
    dateWatched: new Date("2021-03-05"),
  },
  {
    title: "The Bear",
    type: "Series",
    genres: ["Drama", "Comedy"],
    status: "WATCHED",
    rating: 9.4,
    notes: "Intense, raw kitchen energy that turns into pure warmth and growth.",
    synopsis: "A young chef from the fine dining world comes home to Chicago to run his family Italian beef sandwich shop after a heartbreaking death in his family.",
    posterUrl: "https://image.tmdb.org/t/p/w500/6JbtKz0N120x09V6k5Y4nN9F0K3.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/m91vgWrm27xZ04yq4c6tZt36f5B.jpg",
    releaseYear: 2022,
    runtimeMin: 30,
    isTop10: true,
    top10Rank: 9,
    dateWatched: new Date("2024-01-20"),
  },
  {
    title: "Past Lives",
    type: "Movie",
    genres: ["Romance", "Drama"],
    status: "WATCHED",
    rating: 9.2,
    notes: "A quiet, devastating meditation on what could have been.",
    synopsis: "Nora and Hae Sung, two deeply connected childhood friends, are wrested apart after Nora's family emigrates from South Korea. Decades later, they are reunited for one fateful week.",
    posterUrl: "https://image.tmdb.org/t/p/w500/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/619f7w8mN4P1v3yvJ7k4l0V1r7Z.jpg",
    releaseYear: 2023,
    runtimeMin: 106,
    isTop10: true,
    top10Rank: 10,
    dateWatched: new Date("2024-02-14"),
  },
  {
    title: "The Last of Us",
    type: "Series",
    genres: ["Action", "Adventure", "Drama"],
    status: "WATCHLIST",
    rating: null,
    notes: "Queued up next for the weekend binge.",
    synopsis: "20 years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone.",
    posterUrl: "https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2V7JMrRI.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    releaseYear: 2023,
    runtimeMin: 60,
    priority: 1,
  },
  {
    title: "Challengers",
    type: "Movie",
    genres: ["Romance", "Drama"],
    status: "WATCHLIST",
    rating: null,
    notes: "Recommended by friends, need to watch soon.",
    synopsis: "Tennis player-turned-coach Tashi has taken her husband, Art, and transformed him into a world-famous grand slam champion.",
    posterUrl: "https://image.tmdb.org/t/p/w500/H6vke73qEpL2zYvZyYq22ezyeEN.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/ga4OLm4qLxO1YMaoXe0rs0B1Yjm.jpg",
    releaseYear: 2024,
    runtimeMin: 131,
    priority: 2,
  },
];

async function seed() {
  console.log("Seeding sample entries...");
  for (const entry of sampleEntries) {
    await prisma.entry.create({
      data: entry,
    });
  }
  console.log(`Successfully seeded ${sampleEntries.length} entries.`);
  await prisma.$disconnect();
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
